import { Lead, CampaignActivity } from "../models";
import { enrichLeadWithAI, generateStagedOutreachEmail } from "./gemini";
import { fetchWebsiteText } from "./research";

export type StageResult = { stage: number; shouldDraft: boolean; reason?: string };

// Decide the outreach stage from a lead's activity history (see sales memory, Stages 0–5).
export async function detectStage(leadId: string): Promise<StageResult> {
  const activities = await CampaignActivity.findAll({ where: { leadId } });
  if (activities.some(a => a.type === "ReplyReceived")) {
    return { stage: 5, shouldDraft: false, reason: "Lead replied — hand to a human." };
  }
  const sent = activities.filter(a => a.type === "OutreachSent").length;
  if (sent === 0) return { stage: 0, shouldDraft: true };
  if (sent === 1) return { stage: 2, shouldDraft: true };
  if (sent === 2) return { stage: 3, shouldDraft: true };
  if (sent === 3) return { stage: 4, shouldDraft: true };
  return { stage: 5, shouldDraft: false, reason: "Max follow-ups reached." };
}

export type DraftResult =
  | { skipped: true; reason: string }
  | { skipped: false; stage: number; subject: string };

// Research (if needed) + draft the next-stage email per the sales memory. Never sends.
export async function draftOutreachForLead(lead: Lead, senderName: string): Promise<DraftResult> {
  if (["Bounced", "Unsubscribed", "Replied"].includes(lead.status)) {
    return { skipped: true, reason: `Lead status is ${lead.status}` };
  }
  // Deliverability gate — skip catch-all / unverified addresses
  if (lead.emailStatus && /catch.?all|unverified|invalid/i.test(lead.emailStatus)) {
    return { skipped: true, reason: `Email status: ${lead.emailStatus}` };
  }

  const { stage, shouldDraft, reason } = await detectStage(lead.id);
  if (!shouldDraft) return { skipped: true, reason: reason || "Nothing to draft" };

  // Pull live content from the lead's own website (best-effort) for real personalization
  const websiteText = await fetchWebsiteText(lead.website);

  // Ensure research exists (grounded in Google Search + website); persist so it's reusable / visible
  let enrichment = lead.enrichment;
  if (!enrichment) {
    try {
      const e = await enrichLeadWithAI(lead.name, lead.company, {
        title: lead.title,
        industry: lead.industry,
        keywords: lead.keywords,
        technologies: lead.technologies,
        website: lead.website,
        websiteText,
      });
      if (e && !e.error) {
        enrichment = e;
        await lead.update({ enrichment });
      }
    } catch {
      enrichment = null;
    }
  }

  const draft = await generateStagedOutreachEmail(lead, { stage, enrichment, senderName, websiteText });
  await lead.update({
    aiDraft: draft.body,
    draftSubject: draft.subject,
    draftApproved: false,
  });
  await CampaignActivity.create({
    leadId: lead.id,
    campaignId: lead.campaignId,
    type: "DraftGenerated",
    content: `Stage ${stage} draft generated by sales agent.`,
    generatedContent: JSON.stringify(draft),
  });

  return { skipped: false, stage, subject: draft.subject };
}
